### ISSUE TITLE
译文排版规则指北目录链接问题

### ISSUE THREAD

**Issue by FannyXL** [lujun9972/emacs-document#24]
https://github.com/lujun9972/emacs-document/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97

点击一个目录项，比如“空格”会跳到 Home 而不是该内容。

**Comment by FannyXL** [comment]
[译文排版规则指北_修改.zip](https://github.com/lujun9972/emacs-document/files/902687/_.zip)

改了一下这个org文件，现在应该可以了。

**Comment by samrayleung** [comment]
收到，谢谢你的纠正

**Comment by FannyXL** [comment]
：）
