### ISSUE TITLE
几个问题需要请教

### ISSUE THREAD

**Issue by LdBeth** [lujun9972/emacs-document#29]
## 是否有必要把原文作为 注释 保留？

我的习惯是先把原文注释掉（用 `#` 单行注释或者 `#+BEGIN_COMMENT` 多行注释），然后在原文件上下对照翻译。
考虑到如果翻译出现纰漏，能直接有原文对照更方便，是否应该将原文作为注释在翻译完成的文件中保留呢？

----

## 另外一个问题

鉴于 Org 在 GitHub 上有渲染中文空格问题，上传的文件中文段落是不换行的吗？

**Comment by lujun9972** [comment]
第一个问题，无所谓了，只要你习惯就好。

第二个问题，没太明白，能给个例子么？

**Comment by samrayleung** [comment]
我想我理解你第二个问题的意思，你是指 github 在解析 org的时候会自动换行，如果你在org 文件中也换行了，可能会导致渲染出来的页面出现多个换行空格的现象，不知道我是否理解正确？如果是这样的话，我自己一般都是有在 org 文件换行的，因为我习惯了超过 80 个字符就换行，虽说渲染出来有一点过多的空格，但是个人认为影响不大。翻译指南也没有对此做硬性要求

**Comment by LdBeth** [comment]
Ok ，感谢解答。
