### ISSUE TITLE
十倍提升 Emacs 速度使用？

### ISSUE THREAD

**Issue by mydearxym** [lujun9972/emacs-document#3]
感谢分享！

看了 [十倍提升 Emacs 速度](https://github.com/lujun9972/emacs-document/blob/master/emacs-common/%E5%8D%81%E5%80%8D%E6%8F%90%E5%8D%87Emacs%E6%80%A7%E8%83%BD.org?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io) 有几个使用上的问题

1.是不是每次使用的时候要使用 `emacs2ram start/restore`  ?
2. 如果本身机器的内容只有 8G ，只能分一个 G 给 Emacs , 这样速度提升是否有效呢？

PS: Mac 10.12, Emacs 25.1, Spacemacs 0.105.x

**Comment by lujun9972** [comment]
1. 每次重启后,内存中的内容会消失,因此在重启后总是要运行一次start,同理,在重启前需要运行一次restore来将修改同步回来.
2. 只要内存足够放你的配置,理论上速度都应该会提升的.
