### ISSUE TITLE
No such file or directory, helm-rtags

### ISSUE THREAD

**Issue by jusonqiu** [lujun9972/emacs-document#31]
启动的时候出现下面的错误：
Error (use-package): rtags :config: Cannot open load file: No such file or directory, helm-rtags

**Comment by lujun9972** [comment]
什么意思？

**Comment by LdBeth** [comment]
> 什么意思？

我记得你似乎在 emacs-china 安利过 rtags。

**Comment by samrayleung** [comment]
https://github.com/Andersbakken/rtags  我尝试了一下，是可以在　melpa 上找到　helm-rtags 这个包的

**Comment by lujun9972** [comment]
我怎么不记得安利过rtags…

而且跟这个项目有啥关系？
