### ISSUE TITLE
Typo in 文学编程简介

### ISSUE THREAD

**Issue by Ynjxsjmh** [lujun9972/emacs-document#353]
https://github.com/lujun9972/emacs-document/blob/master/org-mode/%E6%96%87%E5%AD%A6%E7%BC%96%E7%A8%8B%E7%AE%80%E4%BB%8B.org

> 为什么使用Org?
> Knuth最开始认为文学编程只需要使用最简单功能的编辑器就行, 因为他只是谢了noweb程序来创建文学编程文档并从中抽取源代码.

谢了 -> 写了

BTW: 文章源地址只在 raw 文件里可见，是否考虑在 README 里添加此信息？

**Comment by lujun9972** [comment]
谢谢反馈，我试试在README中加个原文的链接吧
