### ISSUE TITLE
请问如何有条件的 tangle？

### ISSUE THREAD

**Issue by shjanken** [lujun9972/emacs-document#4]
比如我有两个 `emacs` 的配置文件，分别针对 `prelude` 和 `spacemacs`.
请问如何只创建出来 `prelude` 或者 `spacemacs`的配置文件？

谢谢

**Comment by lujun9972** [comment]
你好,不是很懂你的意思.
不过如果针对prelude和spacemacs的配置是分属两个文件的话,那么可以用 C-u C-u C-c Cv C-t 来只tangle针对preldue或spacemacs的配置. 不知道你要的是这个不?

**Comment by shjanken** [comment]
你好
感谢您的回答，不好意思我没有表述清楚的我的场景。
我在同一个 org 文件中定义了两个代码块，分别对应 spacemacs 和 prelude 的配置，我希望能在 tangle 的时候能单独创建 spacemacs 的配置或者 prelude 的配置。毕竟这两个配置文件文件的文件名，位置内容都不同。
而现在如果我在我的 dotfile.org 文件中按下 `C-c C-v t` 之后，定义在这个 `dotfile.org` 中的两个代码块就都生成了（两个 emacs 的配置文件）。

**Comment by shjanken** [comment]
你好
今天看了下帮助文档，发现只要使用 `C-u C-c C-v t` 就可以实现只创建当前代码块对应的 `dotfile`. 
帮助文档果然很重要，谢谢
