### ISSUE TITLE
建议：给项目加上tag标签

### ISSUE THREAD

**Issue by ascrutae** [lujun9972/emacs-document#46]
给项目加上emacs tag，这样有助于搜索

**Comment by ZucchiniY** [comment]
你是用哪个工具进行搜索啊？

**Comment by ascrutae** [comment]
Github自带的搜索，每一个工程都有topic，可以建议加上topic，这样方便搜索

**Comment by ascrutae** [comment]
`emacs`至少要有的，具体可以参考别的emacs工程的topic: https://github.com/topics/emacs

**Comment by lujun9972** [comment]
好的，已经加了一些topic了，谢谢
