### ISSUE TITLE
仓库中的几个文件名带有冒号  无法在windows上检出

### ISSUE THREAD

**Issue by c0001** [lujun9972/emacs-document#49]
> 平台： win10 专业版
>  最新版本的 ·git for windows·

**如下文件名在windows的文件系统中命名非法：**
1. elisp-common/PComplete:根据上下文环境进行补全.org
2. elisp-common/el-search:为emacs-lisp-mode提供基于表达式的增量搜索.org
3. emacs-common/EmacsWiki: Programmable Completion.org
4. org-mode/用Org-mode写作:如何导出部分内容.org

这里的四个文件带有冒号为其文件名的一部分，因此无法在windows中检出（操作系统不支持）。

**Comment by lujun9972** [comment]
改成个什么字符比较好呢，还真头疼...不知道windows上支持哪些字符

**Comment by Liu233w** [comment]
改成全角冒号？

**Comment by c0001** [comment]
为什么要冒号，其实我觉得小横杠就不错了:)

**Comment by lujun9972** [comment]
可惜现在手头没有电脑，过几天我改一下

**Comment by c0001** [comment]
新年好 同 手机 在线

**Comment by lujun9972** [comment]
新年快乐ヘ( ^o^)ノ＼(^_^ )

**Comment by lujun9972** [comment]
已经改名
