### ISSUE TITLE
希望帮忙翻译

### ISSUE THREAD

**Issue by samrayleung** [lujun9972/emacs-document#5]
1. 我希望可以帮忙一起翻译一些文档,不知道应该怎么做呢
2. 一个小建议,或许译文底部可以加上原文的链接

**Comment by lujun9972** [comment]
欢迎欢迎(｡･ω･｡)ﾉ♡

你只要在平时上网的时候看到有好的外文博客就可以翻译过来放在这里。

当然你也可以直接翻译raw下面的文件。不过最好事前跟我说下，免得翻译重复了。

至于文件格式，就不做要求了，你可以用org也可以用md或者其他你喜欢的格式。但是在文件内容里一定要包含原链接的地址(比如我是存在#+url这个元数据里的)，至于是否要显示出来，我觉得就随意了。

**Comment by samrayleung** [comment]
好的,我的翻译水平只是很一般,希望多多体谅一下哈 :)
